
GET http://localhost:3030/users

########################################

GET http://localhost:3030/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2MTU3MzY4OTksImV4cCI6MTYxNTczNzQ5OX0.YGKaNTuAxbcp5Hk2gZv4eiT6zC0d1V0BPLVhXr7ApmM

########################################

POST http://localhost:3030/sign-up
Content-Type: application/json

{
  "name": "Jakub",
  "password": "password"
}

########################################

POST http://localhost:3030/login
Content-Type: application/json

{
  "name": "Jakub",
  "password": "password"
}

########################################

POST  http://localhost:3030/create-post
Content-Type: application/json

{
  "author": "Jožino",
  "title": "Post 5"
}

########################################

POST http://localhost:3030/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2MTU3Mzc2OTV9.ZC-yK1u1_xTR8eIme483xpZvRxeR9QqeyvOhN2rGwrg"
}

########################################

POST http://localhost:3030/sign-out
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2MTU3Mzc2OTV9.ZC-yK1u1_xTR8eIme483xpZvRxeR9QqeyvOhN2rGwrg"
}